CREATE TABLE `bots` (
  `id` int NOT NULL AUTO_INCREMENT,
  `uuid` varchar(36) NOT NULL,
  `user_id` int NOT NULL,
  `bot_address` int NOT NULL,
  `name` varchar(100) NOT NULL,
  `target_price` float NOT NULL,
  `min_amount` float NOT NULL,
  `max_amount` float NOT NULL,
  `min_delay` int NOT NULL,
  `max_delay` int NOT NULL,
  `target_balance` float NOT NULL DEFAULT '0',
  `holder_percent` float NOT NULL DEFAULT '0',
  `slippage_tolerance` double NOT NULL DEFAULT '5',
  `delay_to_start` int NOT NULL DEFAULT '0',
  `type` varchar(4) NOT NULL,
  `active` tinyint NOT NULL DEFAULT '0',
  `active_airdrop` tinyint NOT NULL DEFAULT '0',
  `need_wait` tinyint NOT NULL DEFAULT '0',
  `is_hidden` tinyint NOT NULL DEFAULT '0',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`,`uuid`),
  UNIQUE KEY `idjobs_UNIQUE` (`id`),
  UNIQUE KEY `uuid_UNIQUE` (`uuid`),
  UNIQUE KEY `bot_address_UNIQUE` (`bot_address`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
