CREATE TABLE `seed_bots` (
  `id` int NOT NULL AUTO_INCREMENT,
  `uuid` varchar(36) NOT NULL,
  `user_id` int NOT NULL,
  `name` varchar(100) NOT NULL,
  `helper_private_key` varchar(255) NOT NULL,
  `account_private_key` varchar(255) NOT NULL,
  `account_friendly_name` varchar(255) DEFAULT NULL,
  `destiny_address` varchar(42) NOT NULL,
  `destiny_friendly_name` varchar(255) DEFAULT NULL,
  `token_name` varchar(100) NOT NULL,
  `token_symbol` varchar(20) NOT NULL,
  `token_address` varchar(42) NOT NULL,
  `amount` float NOT NULL,
  `cycles` int NOT NULL DEFAULT '10',
  `cycle_delay` int NOT NULL DEFAULT '180',
  `cycle_ghosts` int NOT NULL DEFAULT '15',
  `airdrop_time` int NOT NULL DEFAULT '60',
  `actual_cycle` int NOT NULL DEFAULT '0',
  `active` tinyint NOT NULL DEFAULT '0',
  `is_hidden` tinyint NOT NULL DEFAULT '0',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`,`uuid`),
  UNIQUE KEY `id_seed_bots_UNIQUE` (`id`),
  UNIQUE KEY `uuid_seed_bots_UNIQUE` (`uuid`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
