

export interface TradeBot {
  id?: number,
  uuid: string,
  user_id: number,
  name: string,
  helper_private_key: string,
  account_private_key: string,
  account_friendly_name: string,
  destiny_address: string,
  destiny_friendly_name: string,
  token_name: string,
  token_symbol: string,
  token_address: string,
  target_price: number,
  spent_balance?: number,
  min_amount: number,
  max_amount: number,
  min_delay: number,
  max_delay: number,
  target_balance: number,
  holder_percent: number,
  slippage_tolerance: number,
  delay_to_start?: number,
  strategy: string,
  mode: string,
  max_queue: number,
  cycles: number,
  cycle_delay: number,
  cycle_ghosts: number,
  work_start: string,
  work_end: string,
  airdrop_time: number,
  active?: boolean,
  is_hidden?: boolean
}