CREATE TABLE `transactions` (
  `id` int NOT NULL AUTO_INCREMENT,
  `hash` varchar(255) DEFAULT NULL,
  `bot_address` int DEFAULT NULL,
  `distribution_bot_wallet` int DEFAULT NULL,
  `trade_bot` int DEFAULT NULL,
  `seed_bot` int DEFAULT NULL,
  `bot_execution` int DEFAULT NULL,
  `message` longtext,
  `result` longtext,
  `start_matic` decimal(30,18) NOT NULL,
  `end_matic` decimal(30,18) NOT NULL,
  `symbol_selected_token` varchar(20) NOT NULL,
  `start_selected_token` decimal(30,18) NOT NULL,
  `end_selected_token` decimal(30,18) NOT NULL,
  `new_wallet_address` varchar(42) DEFAULT NULL,
  `new_wallet_private_key` varchar(80) DEFAULT NULL,
  `from_address` varchar(42) NOT NULL,
  `to_address` varchar(42) NOT NULL,
  `type` varchar(45) NOT NULL,
  `airdrop_status` tinyint NOT NULL DEFAULT '0',
  `need_airdrop` tinyint NOT NULL DEFAULT '0',
  `status` tinyint NOT NULL,
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE KEY `id_UNIQUE` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;