CREATE TABLE `volume_bots` (
  `id` int NOT NULL AUTO_INCREMENT,
  `uuid` varchar(36) NOT NULL,
  `user_id` int NOT NULL,
  `name` varchar(100) NOT NULL,
  `account_private_key_buy` varchar(255) NOT NULL,
  `account_private_key_sell` varchar(255) NOT NULL,
  `private_key_buy_friendly_name` varchar(255) DEFAULT NULL,
  `private_key_sell_friendly_name` varchar(255) DEFAULT NULL,
  `token_name` varchar(100) NOT NULL,
  `token_symbol` varchar(20) NOT NULL,
  `token_address` varchar(42) NOT NULL,
  `min_amount` float NOT NULL,
  `max_amount` float NOT NULL,
  `min_delay` int NOT NULL,
  `max_delay` int NOT NULL,
  `sell_swap_times` int NOT NULL DEFAULT '1',
  `slippage_tolerance` double NOT NULL DEFAULT '5',
  `delay_to_start` int NOT NULL DEFAULT '0',
  `airdrop_time` int NOT NULL DEFAULT '60',
  `active_airdrop` tinyint NOT NULL DEFAULT '0',
  `need_wait` tinyint NOT NULL DEFAULT '0',
  `is_hidden` tinyint NOT NULL DEFAULT '0',
  `active` tinyint NOT NULL DEFAULT '0',
  `created_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
